import { createApp } from 'vue';
import App  from  './App.vue';
import FriendContact from './components/ContactDetails.vue';
import AddFriend from './components/AddFriend.vue';
import BaseButton from './components/BaseButton.vue';
const appA=createApp(App);
appA.component('friend-contact',FriendContact);
appA.component('add-friend',AddFriend);
appA.component('base-button',BaseButton);
appA.mount('#app');
